name: GitHub Actions Demo
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout кода
        uses: actions/checkout@v3

      - name: Установка Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Установка зависимостей
        run: npm install

      - name: Запус сборки prod
        run: npm run build:prod

      - name: Запуск линтера TypeScript
        run: npm run lint:ts

      - name: Запуск линтера SCSS
        run: npm run lint:scss

      - name: Запуск юнит-тестов
        run: npm run test:unit

      - name: Запуск сборки sb
        run: npm run sb:build

      - name: Запуск ui-тестов (screenshot)
        run: npm run test:ui:ci
